# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.7
    - dl1_data_handler=0.10.4
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-GPU v1.15.3
        - tensorflow_gpu==1.15.3

