# conda env create -f environment.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.10
    - dl1_data_handler=0.10.8
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        - ctaplot
        - numba>=0.56.2
        - tensorflow>=2.9,<2.10
        - tf2onnx>=1.12
        - pydot
        - pyirf>=0.7
