# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.6
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-GPU v1.15.3
        - tensorflow_gpu==1.15.3
        # ctaplot v0.5.3
        - ctaplot==0.5.3
