# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
    #- nvidia
dependencies:
    - python=3.8
    - dl1_data_handler=0.10.4
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    #- cudatoolkit=11
    #- cudnn=8
    #- cupti=11
    #- cuda-nvcc
    - pip:
        # TensorFlow-GPU 
        - tensorflow_gpu
        - pydot

