# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.6
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-CPU v1.15.3
        - tensorflow==1.15.3
        # ctaplot v0.5.3
        - ctaplot==0.5.3
