# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.7
    - dl1_data_handler=0.8.3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-CPU v1.15.3
        - tensorflow==1.15.3
        - ctaplot
