# conda env create -f environment-cpu.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.8
    - dl1_data_handler=0.10.4
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-CPU
        - tensorflow
        - pydot
