Logging:
    model_directory: '/home/tjark/deeplearning/icrc2021/logs/NectarCam/'
Data_format: 'stage1'
Data:
    file_list: '/home/tjark/deeplearning/icrc2021/balanced_small.txt'
    mode: 'stereo'
    selected_telescope_types: ['MST_MST_NectarCam']
    # Prod5 layout S-M5C5-13MSTs40SSTs-MSTF -> NectarCam
    selected_telescope_ids:  {"MST_MST_NectarCam": [100, 101, 103, 106, 107, 129, 111, 114, 115, 116, 119, 120, 121]}
    shuffle: true
    seed: 1234
    image_channels: ['image', 'peak_time']
    #image_channels: ['image', 'peak_time', 'image_mask']
    mapping_settings:
        camera_types: ['NectarCam']
        mapping_method:
            'NectarCam': 'bilinear_interpolation'
        padding:
            'NectarCam': 2
        mask_interpolation: false
    event_info:
        - 'true_shower_primary_id'
    transforms:
        - 
            name: 'ShowerPrimaryID'
        -
            name: 'SortTelescopes'
            args: {'sorting':'size', 'tel_desc': 'MST_MST_NectarCam'}
Input:
    seed: 1234
    batch_size: 16
    prefetch_to_device:
        device: "/gpu:0"
        buffer_size: null
Model:
    model_directory: '/home/tjark/deeplearning/ctlearn/ctlearn/default_models/'
    model: {module: 'cnn_rnn', function: 'cnn_rnn_model'}
    tasks:
        particletype: {class_names: ['proton', 'gamma'], fc_head: [2], weight: 1.0}
Model Parameters:
    res_net:
        network: {module: 'resnet_engine', function: 'stacked_res_blocks'}
        #init_layer: {filters: 64, kernel_size: 7, strides: 1}
        #init_max_pool: {size: 3, strides: 2}
        pretrained_weights: null
    single_cnn:
        network: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
    cnn_rnn:
        cnn_block: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
        dropout_rate: 0.5
    variable_input_model:
        cnn_block: {module: 'basic', function: 'conv_block'}
        telescope_combination: 'feature_maps'
        network_head: {module: 'basic', function: 'conv_head'}
        pretrained_weights: null
    basic:
        conv_block:
            layers:
                - {filters: 32, kernel_size: 3}
                - {filters: 32, kernel_size: 3}
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
            max_pool: {size: 2, strides: 2}
            bottleneck: null
            batchnorm: false
        fc_head:
            layers: [1024, 512, 256, 128, 64]
            batchnorm: false
        conv_head:
            layers:
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
                - {filters: 256, kernel_size: 3}
            final_avg_pool: true
            batchnorm: false
        batchnorm_decay: 0.99
    resnet_engine:
        stacked_res_blocks:
            residual_block: 'bottleneck'
            architecture:
                - {filters: 48, blocks: 2}
                - {filters: 96, blocks: 3}
                - {filters: 128, blocks: 3}
                - {filters: 256, blocks: 3}
    #attention: {mechanism: 'Squeeze-and-Excitation', ratio: 16}
Training:
    validation_split: 0.1
    num_epochs: 10
    optimizer: 'Adam'
    adam_epsilon: 1.0e-8
    base_learning_rate: 0.0001
    scale_learning_rate: false
    apply_class_weights: true
    variables_to_train: null
Evaluation:
    tensorflow: true
    start_delay_secs: 5000
    throttle_secs: 5000
Checkpoints:
    save_checkpoints_steps: 5000
Prediction:
    file: 'particle_nocut_cnnrnn'
    prediction_file_lists:
        'proton': '/home/tjark/deeplearning/LST_mono_testing_protons.txt'
        'gamma_diffuse': '/home/tjark/deeplearning/LST_mono_testing_diffusegammas.txt'
        'gamma_pointlike': '/home/tjark/deeplearning/LST_mono_testing_pointlikegammas.txt'
        'electron': '/home/tjark/deeplearning/LST_mono_testing_electrons.txt'
    save_labels: true
    save_identifiers: true
TensorFlow:
    run_TFDBG: false
