Logging:
    model_directory: '/data3/users/tjark/particle_testlog_TRNRNN/'
#Data_format: 'dl1dh'
Data_format: 'stage1'
Data:
    file_list: '/data3/users/tjark/dl1-data-handler/runlist.txt'
    mode: 'stereo'
    #selected_telescope_types: ['LST_MAGIC_MAGICCam']
    selected_telescope_types: ['LST_LST_LSTCam']
    multiplicity_selection: {"LST_LST_LSTCam": 4}
    shuffle: true
    seed: 1234
    image_channels: ['image', 'peak_time', 'cleaned_image', 'cleaned_time']
    mapping_settings:
        #camera_types: ['MAGICCam']
        camera_types: ['LSTCam']
        mapping_method:
            'LSTCam': 'bilinear_interpolation'
            'MAGICCam': 'bilinear_interpolation'
        padding:
            'LSTCam': 2
            'MAGICCam': 2
    #parameter_selection: 
    #    - {tel_type: "LST_LST_LSTCam", col_name: "hillas_intensity", min_value: 50.0}
    #    - {tel_type: "LST_LST_LSTCam", col_name: "leakage_intensity_width_2", max_value: 0.2}
    event_info:
        - 'true_shower_primary_id'
    transforms:
        - 
            name: 'ShowerPrimaryID'
        -
            name: 'SortTelescopes'
            args: {'sorting':'size'}
Input:
    seed: 1234
    batch_size: 16
    prefetch_to_device:
        device: "/gpu:0"
        buffer_size: null
Model:
    model_directory: '/data3/users/tjark/ctlearn/ctlearn/default_models/'
    model: {module: 'resnet_rnn', function: 'resnet_rnn_model'}
    tasks:
        particletype: {class_names: ['proton', 'gamma'], fc_head: [2], weight: 1.0}
Model Parameters:
    res_net:
        network: {module: 'resnet_engine', function: 'stacked_res_blocks'}
        #init_layer: {filters: 64, kernel_size: 7, strides: 1}
        #init_max_pool: {size: 3, strides: 2}
        pretrained_weights: null
    resnet_rnn:
        network: {module: 'resnet_engine', function: 'stacked_res_blocks'}
        #init_layer: {filters: 64, kernel_size: 7, strides: 1}
        #init_max_pool: {size: 3, strides: 2}
        pretrained_weights: '/data3/users/tjark/particle_testlog/'
        trainable_backbone: false
        dropout_rate: 0.5
    single_cnn:
        network: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
    cnn_rnn:
        cnn_block: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
        dropout_rate: 0.5
    variable_input_model:
        cnn_block: {module: 'basic', function: 'conv_block'}
        telescope_combination: 'feature_maps'
        network_head: {module: 'basic', function: 'conv_head'}
        pretrained_weights: null
    basic:
        conv_block:
            layers:
                - {filters: 32, kernel_size: 3}
                - {filters: 32, kernel_size: 3}
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
            max_pool: {size: 2, strides: 2}
            bottleneck: null
            batchnorm: false
        fc_head:
            layers: [1024, 512, 256, 128, 64]
            batchnorm: false
        conv_head:
            layers:
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
                - {filters: 256, kernel_size: 3}
            final_avg_pool: true
            batchnorm: false
        batchnorm_decay: 0.99
    resnet_engine:
        stacked_res_blocks:
            residual_block: 'bottleneck'
            architecture:
                - {filters: 48, blocks: 2}
                - {filters: 96, blocks: 3}
                - {filters: 128, blocks: 3}
                - {filters: 256, blocks: 3}
    attention: {mechanism: 'Squeeze-and-Excitation', ratio: 16}
Training:
    validation_split: 0.05
    num_epochs: 5
    optimizer: 'Adam'
    adam_epsilon: 1.0e-8
    base_learning_rate: 0.0001
    scale_learning_rate: false
    apply_class_weights: false
    variables_to_train: null
Evaluation:
    tensorflow: true
    start_delay_secs: 5000
    throttle_secs: 5000
Checkpoints:
    save_checkpoints_steps: 5000
Prediction:
    file: 'LSTCam_particle_TRNRNN_lowcut_mult4'
    prediction_file_lists:
        'proton': '/home/tjark/icrc2021/proton_lstmeeting_test.txt'
        'diffuse': '/home/tjark/icrc2021/gamma-diffuse_lstmeeting_test.txt'
        'gamma': '/home/tjark/icrc2021/gamma_lstmeeting_test.txt'
        'electron': '/home/tjark/icrc2021/electron_lstmeeting_test.txt'
    save_labels: false
    save_identifiers: false
TensorFlow:
    run_TFDBG: false
