name: CTLearn installation as a Python package using Conda

on: [push]

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            install-method: conda

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare conda installation
        if: matrix.install-method == 'conda'
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          # fix mamba error that the directory does not exist
          mkdir -p ~/conda_pkgs_dir/cache
          # setup correct python version
          sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml

      - name: Conda setup
        if: matrix.install-method == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          activate-environment: "ctlearn"
          environment-file: environment.yml

      - name: Install dependencies
        run: |
          python --version
          pip install codecov pytest-cov flake8 pytest-xdist 'coverage!=6.3.0'
          pip install .[all]
          pip freeze

      - name: Static codechecks
        # need to use a login shell for the conda setup to work
        shell: bash -leo pipefail {0}
        run: |
          flake8 ctlearn
