name: CTLearn installation as a Python package using Conda

on: [push]

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pythonv: [3.8, 3.9, '3.10']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.pythonv }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pythonv }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Add conda to system library path
      run: |
	echo $CONDA/lib >> $LD_LIBRARY_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Install CTLearn
      run: |
        pip install .
